name:                winter-of-haskell
version:             0.1.0.0
github:              "jannicbeck/winter-of-haskell"
license:             BSD3
author:              "Jannic Beck, Nicolas Beck"
maintainer:          "jannicbeck@gmail.com"
copyright:           "2018 Beck"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jannicbeck/winter-of-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- http-types
- postgresql-simple
- text
- wai
- warp
- time
- containers

library:
  source-dirs: src

executables:
  winter-of-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - winter-of-haskell
    - aeson
    - http-types
    - text
    - time
    - wai
    - warp
    - containers

tests:
  winter-of-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - winter-of-haskell
    - hspec
